--------------------------------------------------------------------------------
--     UUIDs - An implementation of https://www.ietf.org/rfc/rfc9562.html     --
--------------------------------------------------------------------------------
--  Copyright (c) 2025 AJ Ianozi                                              --
--  Licensed under the MIT License.  See attached LICENSE for details.        --
--------------------------------------------------------------------------------
--  ****h* UUIDs/UUIDs.V7
--  SOURCE
package UUIDs.V7 is
--  DESCRIPTION
--    UUIDv7 as described in RFC-9562 5.7:
--    https://www.ietf.org/rfc/rfc9562.html#section-5.7
--  ****

   --  ****f* UUIDs.V7/V7.UUID7
   --  SOURCE
   function UUID7 return UUID;
   --  FUNCTION
   --    UUIDv7 features a time-ordered value field derived from the Unix Epoch
   --    timestamp in miliseconds to occupy the 48 most significant bits
   --    followed by the remainder of the field being filled with truely random
   --    or pseudorandom data.  Generally UUIDv7 has improved entropy over
   --    UUIDv1 or UUIDv6 as well as better database locality.
   --  OPTIONS
   --    The default source of randomness is a pseudorandom number generator.
   --    If all random data should be retrieved from system random, refer to
   ---   UUIDs/Settings.Set_Random
   --  SEE ALSO
   --    Please see RFC-9562 5.8 for a full description:
   --    https://www.ietf.org/rfc/rfc9562.html#section-5.7
   --  RETURN VALUE
   --    UUIDs.UUID - The UUIDv7 generated by the function.
   --  EXAMPLE
   --    --  Generate a UUID based on the current time.
   --    My_UUID : UUID := V7.UUID7;
   --  ****

end UUIDs.V7;