--------------------------------------------------------------------------------
--     UUIDs - An implementation of https://www.ietf.org/rfc/rfc9562.html     --
--------------------------------------------------------------------------------
--  Copyright (c) 2025 AJ Ianozi                                              --
--  Licensed under the MIT License.  See attached LICENSE for details.        --
--------------------------------------------------------------------------------
--  ****h* UUIDs/UUIDs.V4
--  SOURCE
package UUIDs.V4 is
--  DESCRIPTION
--    UUIDv4 as described in RFC-9562 5.4:
--    https://www.ietf.org/rfc/rfc9562.html#section-5.4
--  ****

   --  ****f* UUIDs.V4/V4.UUID4
   --  SOURCE
   function UUID4 return UUID;
   --  FUNCTION
   --    UUIDv4 is meant for generating UUIDs truly random or  pseudorandom
   --    numbers.  When called, all 128 bits of data are generated randomly
   --    sans the variant and version fields.
   --  RETURN VALUE
   --    UUIDs.UUID - The UUIDv4 generated by the function.
   --  OPTIONS
   --    The default source of randomness is a pseudorandom number generator.
   --    If all random data should be retrieved from system random, refer to
   --    UUIDs/Settings.Set_Random
   --  SEE ALSO
   --    Please see RFC-9562 5.4 for a full description:
   --    https://www.ietf.org/rfc/rfc9562.html#section-5.4
   --  EXAMPLE
   --    --  Generate a UUID based on purely random data.
   --    My_UUID : UUID := V4.UUID4;
   --  ****

end UUIDs.V4;